resources:
  pipelines:
  - pipeline: version
    source: threat-intel-automation-version
    trigger: true
pool:
  vmImage: ubuntu-22.04

variables:
  - name: ecr_registry
    value: 766012994355.dkr.ecr.ap-southeast-2.amazonaws.com
  - name: ecr_repository
    value: threat-intel-automation

stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_Push
    steps:
    - script: |
        wget https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/deb/latest/aws-signer-notation-cli_amd64.deb
        sudo dpkg -i -E aws-signer-notation-cli_amd64.deb
      name: InstallAwsSigner
    - checkout: self
      persistCredentials: true
    - script: |
        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "${latestTag}"
        echo "##vso[task.setvariable variable=version;isOutput=true]$latestTag"
      name: version
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: AWSShellScript@1
      displayName: "Docker Build"
      inputs:
        awsCredentials: "weshealth-seclog"
        disableAutoCwd: true
        regionName: "ap-southeast-2"
        scriptType: inline
        inlineScript: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin "$(ecr_registry)"
          docker build -f Dockerfile -t "$(ecr_registry)"/"$(ecr_repository)":"$(version.version)" .
          docker push "$(ecr_registry)"/"$(ecr_repository)":"$(version.version)"
        workingDirectory: $(Build.SourcesDirectory)

- stage: TerraformDeploy
  jobs:
  - deployment: TerraformDependancy
    variables:
      version: $[ stageDependencies.Docker.Build_Push.outputs['version.version'] ]
    displayName: Deploy Terraform Dependancy
    environment: 'aws-sec-log'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            persistCredentials: true
          - task: AWSShellScript@1
            displayName: "Terraform Deploy"
            inputs:
              awsCredentials: "weshealth-seclog"
              disableAutoCwd: true
              regionName: "ap-southeast-2"
              scriptType: inline
              inlineScript: |
                terraform init
                terraform apply -auto-approve -input=false -var "image_tag=$(version)"
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
