trigger:
  branches:
    exclude:
    - main
    - master
  paths:
    include:
    - terraform/*

pool:
  vmImage: ubuntu-latest

jobs:
- job: checkov
  strategy:
    matrix:
      TFdir:
        directory: 'terraform'
  displayName: 'Checkov used to security scanning on all branches'
  steps:
  - script: |
      pip3 install checkov
    name: Install
  - script: |
      checkov --quiet -d $(directory) --download-external-modules true
    name: IaCSAST
