trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: OIDC AWS CICD
- name: 'role_arn'
  value: 'arn:aws:iam::766012994355:role/cicd-security-aws-oidc-service-connection'
- name: 'service_name'
  value: 'ti-automation'

stages:
- stage: DockerSecCheck
  jobs:
  - job: DockerContainerScan
    steps:
    - script: |
        docker build -f Dockerfile -t local/"$(service_name)":latest .
      workingDirectory: $(Build.SourcesDirectory)
      name: builddocker
    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
      displayName: 'Get Trivy'
    - script: |
        trivy image -s "HIGH,CRITICAL" local/"$(service_name)":latest
      displayName: 'Run Trivy'
  - job: ScanDockerFile
    displayName: 'Run Terrascan to check for compliance'
    steps:
    - script: |
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xvf terrascan.tar.gz
        install terrascan /usr/local/bin
      displayName: 'Get tools'
    - script: |
        terrascan scan -i docker -f Dockerfile --output junit-xml -c terrascan.toml > terrascan-results.xml
        terrascan scan -i docker -f Dockerfile -o yaml -c terrascan.toml
      displayName: 'Run terrascan'
      workingDirectory: $(System.DefaultWorkingDirectory)
    - task: PublishTestResults@2
      displayName: "Terrascan Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "**/*.xml"
        searchFolder: "$(Build.SourcesDirectory)"
        mergeTestResults: false
        testRuntitle: 'TI Automation Terrascan - "$(System.PullRequest.SourceCommitId)"'
        failTaskOnFailedTests: false
        publishRunAttachments: true

- stage: SASTIaC
  dependsOn: []
  jobs:
  - job: TerraformSAST
    steps:
    - script: |
        pip3 install checkov
      name: CheckovInstall
    - script: |
        checkov --quiet -d terraform --download-external-modules true
        checkov --quiet --output junitxml -d terraform --download-external-modules true > checkov-results.xml
      name: CheckovRun
    - task: PublishTestResults@2
      displayName: "Checkov Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "**/checkov-*.xml"
        searchFolder: "$(Build.SourcesDirectory)"
        mergeTestResults: false
        testRuntitle: 'TI Automation Checkov - "$(System.PullRequest.SourceCommitId)"'
        failTaskOnFailedTests: false
        publishRunAttachments: true

- stage: SASTCode
  dependsOn: []
  jobs:
  - job: Dependency_Scanning_Codebase
    steps:
    - task: AdvancedSecurity-Dependency-Scanning@1
  - job: Code_Scanning_Codebase
    steps:
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: "python"
        querysuite: 'security-extended'
        sourcesfolder: $(System.DefaultWorkingDirectory)/code
    - task: AdvancedSecurity-Codeql-Analyze@1
    - task: AdvancedSecurity-Publish@1

- stage: Terraform
  dependsOn: []
  jobs:
  - job: TerraformCI
    displayName: Terraform CI
    steps:
    - script: |
        export CLIENT_ID="$(client_id)"
        export CLIENT_SECRET="$(client_secret)"
        export TENANT_ID="$(tenant_id)"
        export SCOPE="${CLIENT_ID}""/.default"
        az login --service-principal --allow-no-subscriptions -u "${CLIENT_ID}" -p "${CLIENT_SECRET}" --tenant "${TENANT_ID}"
        export ACCESS_TOKEN=$(az account get-access-token --query "accessToken" --tenant "$(tenant_id)" --scope "${SCOPE}" --output tsv)
        echo "##vso[task.setvariable variable=ACCESS_TOKEN;]$ACCESS_TOKEN"
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      name: aztoken
    - script: |
        aws sts assume-role-with-web-identity --role-arn "${{variables.role_arn}}" --region ap-southeast-2 --web-identity-token "$(ACCESS_TOKEN)" --role-session-name cicd > secrets
        export AWS_ACCESS_KEY_ID="$(cat secrets | jq '.Credentials.AccessKeyId' --raw-output)"
        export AWS_SECRET_ACCESS_KEY="$(cat secrets | jq  '.Credentials.SecretAccessKey' --raw-output)"
        export AWS_SESSION_TOKEN="$(cat secrets | jq '.Credentials.SessionToken' --raw-output)"
        echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID;]$AWS_ACCESS_KEY_ID"
        echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY;]$AWS_SECRET_ACCESS_KEY"
        echo "##vso[task.setvariable variable=AWS_SESSION_TOKEN;]$AWS_SESSION_TOKEN"
        echo "##vso[task.setvariable variable=AWS_REGION;]ap-southeast-2"
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      name: awstoken
    - script: |
        terraform init
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      name: init
    - script: |
        terraform validate
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      name: validate
    - script: |
        terraform plan
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      name: plan
