trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  aws.rolecredential.maxduration: '3600'
  service_name: 'ti-automation'

stages:
- stage: DockerSecCheck
  jobs:
  - job: DockerContainerScan
    steps:
    - script: |
        docker build -f Dockerfile -t tiautomation:ci .
      workingDirectory: $(Build.SourcesDirectory)
      name: builddocker
    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
      displayName: 'Get Trivy'
    - script: |
        trivy image -s "HIGH,CRITICAL" tiautomation:ci
      displayName: 'Run Trivy'
  - job: ScanDockerFile
    displayName: 'Run Terrascan to check for compliance'
    steps:
    - script: |
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xvf terrascan.tar.gz
        install terrascan /usr/local/bin
      displayName: 'Get tools'
    - script: |
        terrascan scan -i docker -f Dockerfile --output junit-xml -c terrascan.toml > terrascan-results.xml
        terrascan scan -i docker -f Dockerfile -o yaml -c terrascan.toml
      displayName: 'Run terrascan'
      workingDirectory: $(System.DefaultWorkingDirectory)
    - task: PublishTestResults@2
      displayName: "Terrascan Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "**/*.xml"
        searchFolder: "$(Build.SourcesDirectory)"
        mergeTestResults: false
        testRuntitle: 'TI Automation Terrascan - "$(System.PullRequest.SourceCommitId)"'
        failTaskOnFailedTests: false
        publishRunAttachments: true

- stage: SASTIaC
  dependsOn: []
  jobs:
  - job: TerraformSAST
    steps:
    - script: |
        pip3 install checkov
      name: CheckovInstall
    - script: |
        checkov --quiet -d terraform --download-external-modules true
        checkov --quiet --output junitxml -d terraform --download-external-modules true > checkov-results.xml
      name: CheckovRun
    - task: PublishTestResults@2
      displayName: "Checkov Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "**/checkov-*.xml"
        searchFolder: "$(Build.SourcesDirectory)"
        mergeTestResults: false
        testRuntitle: 'TI Automation Checkov - "$(System.PullRequest.SourceCommitId)"'
        failTaskOnFailedTests: false
        publishRunAttachments: true

- stage: SASTCode
  dependsOn: []
  jobs:
  - job: Dependency_Scanning_Codebase
    steps:
    - script: |
        python -m pip install --upgrade pip
      name: PipUpgrade
    - task: AdvancedSecurity-Dependency-Scanning@1
  - job: Code_Scanning_Codebase
    steps:
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: "python"
        querysuite: 'security-extended'
        sourcesfolder: $(System.DefaultWorkingDirectory)/code
    - task: AdvancedSecurity-Codeql-Analyze@1
    - task: AdvancedSecurity-Publish@1

- stage: Unittest
  dependsOn: []
  jobs:
  - job: runtest
    steps:
    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        export PYTHONPATH=$(System.DefaultWorkingDirectory)
        echo "PYTHONPATH=$PYTHONPATH"
        python -W ignore -m unittest discover -s tests
      name: Unittest
      workingDirectory: '$(System.DefaultWorkingDirectory)'

- stage: Terraform
  dependsOn: []
  jobs:
  - job: TerraformCI
    displayName: Terraform CI
    steps:
    - task: AWSShellScript@1
      displayName: "Terraform Plan"
      inputs:
        awsCredentials: "weshealth-seclog"
        regionName: "ap-southeast-2"
        scriptType: inline
        disableAutoCwd: true
        inlineScript: |
          terraform init
          terraform validate
          terraform plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
