trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  aws.rolecredential.maxduration: '3600'
  service_name: 'ti-automation'
  snyk_organization_id: 'your-snyk-organization-id'
  snyk_project_name: 'your-snyk-project-name'

stages:
- stage: DockerSecCheck
  jobs:
  - job: DockerContainerScan
    steps:
    - script: |
        docker build -f Dockerfile -t tiautomation:ci .
      workingDirectory: $(Build.SourcesDirectory)
      name: builddocker
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: ''
        testType: 'container'
        dockerImageName: 'tiautomation:ci'
        dockerfilePath: 'Dockerfile'
        severityThreshold: 'medium'
        monitorWhen: 'always'
        failOnIssues: true
        projectName: $(snyk_project_name)
        organization: $(snyk_organization_id)
        failOnThreshold: 'medium'

- stage: SASTIaC
  dependsOn: []
  jobs:
  - job: TerraformSAST
    steps:
    - script: |
        pip3 install checkov
      name: CheckovInstall
    - script: |
        checkov --quiet -d terraform --download-external-modules true
        checkov --quiet --output junitxml -d terraform --download-external-modules true > checkov-results.xml
      name: CheckovRun
    - task: PublishTestResults@2
      displayName: "Checkov Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "**/checkov-*.xml"
        searchFolder: "$(Build.SourcesDirectory)"
        mergeTestResults: false
        testRuntitle: 'TI Automation Checkov - "$(System.PullRequest.SourceCommitId)"'
        failTaskOnFailedTests: false
        publishRunAttachments: true

- stage: SASTCode
  dependsOn: []
  jobs:
  - job: Dependency_Scanning
    steps:
    - script: |
        python -m pip install --upgrade pip
      name: PipUpgrade
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: ''
        testType: 'app'
        severityThreshold: 'medium'
        failOnIssues: true
        projectName: $(snyk_project_name)
        organization: $(snyk_organization_id)
        failOnThreshold: 'medium' #optional, depending on CI
  - job: Code_Scanning_Codebase
    steps:
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: ''
        testType: 'code'
        codeSeverityThreshold: 'medium'
        failOnThreshold: 'medium'
        failOnIssues: true
        projectName: $(snyk_project_name)
        organization: $(snyk_organization_id)

- stage: Unittest
  dependsOn: []
  jobs:
  - job: runtest
    steps:
    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        export PYTHONPATH=$(System.DefaultWorkingDirectory)
        echo "PYTHONPATH=$PYTHONPATH"
        python -W ignore -m unittest discover -s tests
      name: Unittest
      workingDirectory: '$(System.DefaultWorkingDirectory)'

- stage: Terraform
  dependsOn: []
  jobs:
  - job: TerraformCI
    displayName: Terraform CI
    steps:
    - task: AWSShellScript@1
      displayName: "Terraform Plan"
      inputs:
        awsCredentials: "weshealth-seclog"
        regionName: "ap-southeast-2"
        scriptType: inline
        disableAutoCwd: true
        inlineScript: |
          terraform init
          terraform validate
          terraform plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
