trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: versioning
  displayName: 'GitTools versioning'
  steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: 5.x
      preferLatestVersion: true
  - task: gitversion/execute@0
    displayName: Determine Version
    name: version
  - script: |
      echo SemVer: "$(GitVersion.SemVer)"
    displayName: Display output test
  - script: |
      git config --global user.name "CICD"
      git config --global user.email "cicd@contoso.com.au"
      git tag -a "$(GitVersion.SemVer)" -m "Deployment Release"
      git push --tags
    name: Tagging
    workingDirectory: $(Build.SourcesDirectory)
