name: Publish
on:
  release:
    types: [published]
    
env:
  AWS_REGION: "ap-southeast-2"
  REPOSITORY: "ti-automation"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  publish:
    runs-on: ubuntu-20.04
    outputs:
      VERSION: ${{steps.get_version.outputs.VERSION}}
    name: Publish
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Install AWS Signer
      run: |
        wget https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/deb/latest/aws-signer-notation-cli_amd64.deb
        sudo dpkg -i -E aws-signer-notation-cli_amd64.deb
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::371480035879:role/github_actions_cicd
        role-session-name: OIDC_CICD
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build & Push
      id: push
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -f Dockerfile -t ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{steps.get_version.outputs.VERSION}} .
        docker push ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{steps.get_version.outputs.VERSION}}
        IMAGE_SHA=$(aws ecr describe-images --repository-name ${{env.REPOSITORY}} --image-ids imageTag=${{steps.get_version.outputs.VERSION}} --query 'imageDetails[].imageDigest' --output text)
        echo "::set-output name=image_sha::$IMAGE_SHA"
    - name: Sign image with key
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        export NOTATION_USERNAME=AWS
        export NOTATION_PASSWORD=$(aws ecr get-login-password --region ap-southeast-2)
        notation sign ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{steps.get_version.outputs.VERSION}} --plugin "com.amazonaws.signer.notation.plugin" --id "arn:aws:signer:${{env.AWS_REGION}}:12345678912:/signing-profiles/container_image_signing
    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{steps.login-ecr.outputs.registry}}
  terraform:
    runs-on: ubuntu-20.04
    name: Terraform
    needs: publish
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github_actions_cicd
        role-session-name: OIDC_CICD
        aws-region: ${{ env.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.3
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform/
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: terraform/
    - name: Terraform Plan
      id: plan
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: terraform plan -no-color -input=false -var "image_tag=${{needs.publish.outputs.VERSION}}"
      continue-on-error: true
      working-directory: terraform/
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    - name: Terraform Apply
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: terraform apply -auto-approve -input=false -var "image_tag=${{needs.publish.outputs.VERSION}}"
      working-directory: terraform/
